name: Builder

on:
  - pull_request

jobs:
  pull:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: Build
        run: npm run build
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: Test
        run: npm run test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: Lint
        run: npm run lint:check
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: Format
        run: npm run format:check
